### ISSUE TITLE
Potentiometer and Pi0

### ISSUE THREAD

**Issue by withgallantry** [32teeth/GameboyZeroPocket#1]
Fantastic job, just been looking at the Eagle board. How does the potentiometer fit? it looks to be overlapping the Pi0. That's assuming you solder the Pi0 directly to the surface mount pads or is the plan to add a header that elevates the pi?

**Comment by 32teeth** [comment]
Hey @withgallantry 
It's actually stacked.

In the BOM is a 2x20 SMD Male Header
The Pi sits on the header
The trimpot / thumbwheel is in the gap

**Comment by withgallantry** [comment]
Aha, I didn't check the BOM, I just made an assumption based from existing AIO boards. That'll teach me. Thanks for clarifying. Brilliant project, thanks for making this open source.
